# Custom Diffusion (network part), reference: https://github.com/adobe-research/custom-diffusion

unet:
  targets:
    - index: [ 'down_blocks.0', 'down_blocks.1', 'down_blocks.2', 'mid_block', 'up_blocks.1', 'up_blocks.2', 'up_blocks.3' ]
      targets:
        - index: [ 'attentions' ]
          targets:
            - targets:
                - index: [ 'transformer_blocks' ]
                  targets:
                    - targets:
                        - index: [ 'attn1' ]
                          targets:
                            - index: [ 'to_k', 'to_v' ]