unet:
  parameterization: 'eps'
  blocks:
    - index: [ 0, 1, 2, 4, 6, 7, 8 ]
      transformer:
        - cross_attn:
            q:
              low_rank: 4
            k:
              low_rank: 4
            v:
              low_rank: 4
          self_attn:
            q:
              low_rank: 4
            k:
              low_rank: 4
            v:
              low_rank: 4
